### ISSUE TITLE
Some questions on security

### ISSUE THREAD

**Issue by codingchili** [hanjoongcho/aaf-easypassword#7]
Hello,

I noticed that you are encrypting each credential "manually" instead of using the encryption feature in realm. Do you have a reason for this?

Have you considered storing the encryption IV in the application preferences? (The salt variable in the AES utility.) Then users would not need remember to replace it and built the app themselves. It could be generated when it's missing.

The pattern grid has a very low entropy compared to a "password", especially for average patterns of 3-4 edges. How do we deal with brute-force attacks?

**Comment by hanjoongcho** [comment]
The purpose of creating easypassword was that it was not easy to remember the accounts and passwords that were not used very well, so the application was simple to store and to check when I needed it personally.

Encrypting with the aes algorithm in combination with a user-set pattern and a salt string is much safer than storing it as plain text, but it is vulnerable to brute-force attacks, as you mentioned.
Also, I did not use a variable salt string because I can not decode it if the same salt string information is not available when the device is changed during backup and recovery of the realm file to the Google Drive of the user account.
I did not review the realm encryption feature at the time of application development, so the realm was simply used to store data.
In order to be exposed to a brute-force attack, I did not consider brute-force attacks much because we thought that the user's realm db file would have to be taken first.

Unfortunately, since easypassword does not maintenance since the last release on March 27, 2018, there is no room for improvement in this area.
I would like easypassword to help somebody to create a good password management application. :-)

**Comment by codingchili** [comment]
Ah, but the IV could have been included in the realm file then. Ok, I used the realm encryption feature in my password manager and it worked really well - easy to setup. :)

I have been checking out a couple of passwords managers to compare with my own. Thank you for the response and good job with the app. 👍
